name: Django CI

on:
  push:
    branches:
    - master
    - development
    - feature
  pull_request:
    branches: 
    - master
    - development
    - feature

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        db: [ library ]
        python-version: [3.9]
        include:
          - db: library
            db_port: 3306

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3 

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup ENV 
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY}}" >> $GITHUB_ENV
        echo "DB=${{ secrets.DB}}" >> $GITHUB_ENV
        echo "DB_USER=${{ secrets.DB_USER}}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD}}" >> $GITHUB_ENV
        echo "DB_HOST=${{ secrets.DB_HOST}}" >> $GITHUB_ENV
        echo "DB_PORT=${{ secrets.DB_PORT}}" >> $GITHUB_ENV

    - name: Run Migrations
      run: |
        python3 manage.py migrate

    - name: Run Tests
      run: |
        python3 manage.py test
    
