name: Django CI

on:
  push:
    branches:
    - master
    - development
    - feature
  pull_request:
    branches: 
    - master
    - development
    - feature

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test Secrets
      run: echo ${{ secrets.MYSQL_USER }}

    - uses: mirromutth/mysql-action@v1.1
      with:
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: ${{ secrets.MYSQL_DB}} # Optional, default value is "test". The specified database which will be create
        mysql root password: ${{ secrets.MYSQL_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: ${{ secrets.MYSQL_USER }} # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: ${{ secrets.MYSQL_PASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"

    - name: Setup ENV 
      env:
        MYSQL_DATABASE: ${{ secrets.MYSQL_DB}}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_PORT: ${{ secrets.MYSQL_PORT}}

    - name: Set Django Secret Key 
      run: |
        export DJANGO_SECRET_KEY=${{ secrets.SECRET_KEY }}
        set DJANGO_SECRET_KEY

    - name: Check Syntax # check code formatting
      run: pycodestyle --statistics

    - name: Run Migrations
      run: |
        python3 manage.py migrate

    - name: Run Tests
      run: |
        python3 manage.py test
    
