name: Django CI

on:
  push:
    branches:
    - master
    - development
    - feature
  pull_request:
    branches: 
    - master
    - development
    - feature

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: library
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - ${{ secrets.MYSQL_PORT }}
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set Django Secret Key 
      run: |
        export DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
        set DJANGO_SECRET_KEY
    - name: Check Syntax # check code formatting
      run: pycodestyle --statistics
    - name: Run Migrations
      run: |
        python3 manage.py migrate
    - name: Run Tests
      run: |
        python3 manage.py test
    
