name: Django CI

on:
  push:
    branches:
    - master
    - development
    - feature
  pull_request:
    branches: 
    - master
    - development
    - feature

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test Secrets
      run: echo ${{ secrets.MYSQL_USER }}

    - name: Setup MYSQL 
      env:
        MYSQL_DATABASE: ${{ secrets.MYSQL_DB}}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' -u ${{ env.MYSQL_USER }} -p ${{ env.MYSQL_PASSWORD }}
        grant all privileges on *.* to '${{ env.MYSQL_USER }}'@'localhost'

    - name: Set Django Secret Key 
      run: |
        export DJANGO_SECRET_KEY=${{ secrets.SECRET_KEY }}
        set DJANGO_SECRET_KEY

    - name: Check Syntax # check code formatting
      run: pycodestyle --statistics

    - name: Run Migrations
      run: |
        python3 manage.py migrate

    - name: Run Tests
      run: |
        python3 manage.py test
    
